### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by BotAngus** [BotAngus/101-ascensions#1]
- [ ] Lore generation
- [ ] Sect generation
- [ ] NPC generation
- [ ] NPC relationship generation
- [ ] Social hierarchy generation
- [ ] City/village generation
- [ ] Continent/landscape generation
- [ ] Order and laws generation
- [ ] Backstory generation
- [ ] Dynamic systems generation (b.v.b. een stad die bandits aanvalt en de bandits die de merchants aanvallen)
- [ ] Road/route generation
- [ ] City relationship generation
- [ ] Economy generation
- [ ] Flora and fauna generation
- [ ] Wildlife/"ecosystem" generation
- [ ] Event trigger generation (When the player goes to x special event y happens)
- [ ] Quest/quest-line/story generation
- [ ] NPC dialogue generation

**Comment by BotAngus** [comment]
Make a game plan for these tasks.
